command: ["python", "start.py"]
env:
  - name: LAKEBASE_AUTO_PROVISION
    value: 'false'
  - name: USE_LAKEBASE
    value: 'false'
  - name: DEMO_VOLUME_PATH
    value_from: demo-volume
  - name: EXPORT_VOLUME_PATH
    value_from: export-volume
  - name: FINETUNE_DATABRICKS_JOB_ID
    value: '318435402424260'
