"""Generate golden COCO RLE conformance vectors using real pycocotools.

Run in a dev container that has pycocotools installed. Output is committed
as a fixture so the hand-rolled codec in backend/masks.py can be pinned
against the reference implementation without shipping pycocotools.
"""
import base64
import json, random
import numpy as np
from pycocotools import mask as maskUtils

cases = []


def pack_bits(m):
    """Row-major bitmap -> base64 of MSB-first packed bits.

    Recorded so a codec test can pin the exact pixels rather than only
    round-tripping against itself: encode(decode(counts)) == counts passes for
    an implementation that is consistently transposed or flipped, and area is
    invariant to both. The bitmap here comes from pycocotools' own decode, so
    it is independent of any run-length walk under test.
    """
    return base64.b64encode(np.packbits(m.astype(np.uint8), axis=None)).decode("ascii")

def add(name, m):
    """m: HxW uint8 array (0/1). Record uncompressed + compressed forms."""
    m = np.asfortranarray(m.astype(np.uint8))
    h, w = m.shape
    rle = maskUtils.encode(m)                     # compressed
    counts_str = rle["counts"].decode("ascii")
    # uncompressed counts: column-major run lengths starting with background
    flat = m.flatten(order="F")
    counts = []
    prev = 0
    run = 0
    for v in flat:
        if v == prev:
            run += 1
        else:
            counts.append(run)
            prev = v
            run = 1
    counts.append(run)
    assert sum(counts) == h * w
    # Independent bitmap: pycocotools decodes its own compressed form, and we
    # only reorder Fortran -> row-major.
    decoded = np.asarray(maskUtils.decode(rle))
    assert decoded.shape == (h, w)
    assert np.array_equal(decoded, m), "pycocotools did not round-trip its own mask"
    cases.append({
        "name": name,
        "size": [h, w],
        "counts": counts,
        "compressed": counts_str,
        "area": int(maskUtils.area(rle)),
        "bbox": [float(x) for x in maskUtils.toBbox(rle)],
        "pixels_b64": pack_bits(decoded),
    })

# 1. all background
add("all_zero_4x4", np.zeros((4, 4), np.uint8))
# 2. all foreground
add("all_one_4x4", np.ones((4, 4), np.uint8))
# 3. single pixel at origin
m = np.zeros((5, 7), np.uint8); m[0, 0] = 1; add("single_px_origin", m)
# 4. single pixel at far corner
m = np.zeros((5, 7), np.uint8); m[4, 6] = 1; add("single_px_corner", m)
# 5. centre square
m = np.zeros((10, 10), np.uint8); m[3:7, 3:7] = 1; add("centre_square_10x10", m)
# 6. thin vertical stripe (long runs)
m = np.zeros((64, 8), np.uint8); m[:, 3] = 1; add("vstripe_64x8", m)
# 7. thin horizontal stripe (many short runs)
m = np.zeros((8, 64), np.uint8); m[3, :] = 1; add("hstripe_8x64", m)
# 8. checkerboard (worst case: run length 1 everywhere)
m = np.indices((16, 16)).sum(axis=0) % 2; add("checker_16x16", m.astype(np.uint8))
# 9. two disjoint blobs
m = np.zeros((20, 30), np.uint8); m[2:6, 2:8] = 1; m[12:18, 20:28] = 1
add("two_blobs_20x30", m)
# 10. non-square with long runs crossing the 5-bit group boundaries
m = np.zeros((97, 53), np.uint8); m[10:80, 5:40] = 1; add("large_rect_97x53", m)
# 11..15 deterministic pseudo-random masks of assorted sizes
rng = random.Random(28)
for i, (h, w) in enumerate([(13, 29), (31, 17), (64, 64), (7, 101), (128, 3)]):
    m = np.array([[1 if rng.random() < 0.35 else 0 for _ in range(w)]
                  for _ in range(h)], np.uint8)
    add(f"random_{h}x{w}", m)
# 16. circle-ish blob (realistic brush stroke)
yy, xx = np.mgrid[0:48, 0:48]
m = (((yy - 24) ** 2 + (xx - 20) ** 2) < 15 ** 2).astype(np.uint8)
add("disc_48x48", m)
# 17. run lengths that need multi-group LEB128 encoding
m = np.zeros((200, 200), np.uint8); m[50:150, 50:150] = 1
add("big_square_200x200", m)
# 18. asymmetric non-square ring: interior hole, and no symmetry in either
# axis, so a transpose or a flip changes the pixels without changing area.
m = np.zeros((23, 41), np.uint8); m[3:20, 6:35] = 1; m[7:16, 11:22] = 0
add("ring_23x41", m)
# 19. asymmetric staircase: every row a different extent.
m = np.zeros((19, 37), np.uint8)
for r in range(19):
    m[r, r: r + 9] = 1
add("staircase_19x37", m)

out = {
    "_comment": ("Golden COCO RLE vectors generated by tools/gen_rle_fixtures.py "
                 "using pycocotools. Do not hand-edit. pycocotools is a dev-only "
                 "dependency; backend/masks.py must reproduce these exactly."),
    "pycocotools_version": __import__("pycocotools").__version__ if hasattr(__import__("pycocotools"), "__version__") else "unknown",
    "cases": cases,
}
print(json.dumps(out, indent=2))
